# Generated by Django 3.0.6 on 2021-10-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualContributions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('student', models.CharField(max_length=256)),
                ('student_id', models.CharField(max_length=256, null=True)),
                ('done_count', models.IntegerField()),
                ('change_log', models.CharField(default='', max_length=10000)),
            ],
            options={
                'db_table': 'individual_contributions',
            },
        ),
        migrations.CreateModel(
            name='IndividualSummaryAndUrls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('student', models.CharField(max_length=256)),
                ('summary', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'individual_summary_urls',
            },
        ),
        migrations.CreateModel(
            name='JiraCountByTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('to_do', models.IntegerField()),
                ('in_progress', models.IntegerField()),
                ('done', models.IntegerField()),
            ],
            options={
                'db_table': 'jira_count_by_time',
            },
        ),
        migrations.CreateModel(
            name='JiraCycleTimeScatter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('completed', models.CharField(max_length=256)),
                ('cycle_time', models.IntegerField()),
                ('summary', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'jira_cycle_time_data',
            },
        ),
        migrations.CreateModel(
            name='JiraHistogram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('day', models.CharField(max_length=256)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'jira_histogram',
            },
        ),
        migrations.CreateModel(
            name='JiraThroughPut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'jira_throughput',
            },
        ),
        migrations.CreateModel(
            name='Urlconfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('jira_url', models.CharField(max_length=256)),
                ('git_url', models.CharField(max_length=256)),
                ('git_username', models.CharField(max_length=256)),
                ('git_password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'url_config',
            },
        ),
    ]
