# Generated by Django 3.0.6 on 2021-09-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_auto_20210527_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraCycleTimeScatter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('completed', models.CharField(max_length=256)),
                ('cycle_time', models.IntegerField()),
                ('summary', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'jira_cycle_time_data',
            },
        ),
        migrations.CreateModel(
            name='JiraHistogram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('day', models.CharField(max_length=256)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'jira_histogram',
            },
        ),
        migrations.CreateModel(
            name='JiraThroughPut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'jira_throughput',
            },
        ),
        migrations.AddField(
            model_name='individualcontributions',
            name='change_log',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
