# Generated by Django 3.0.6 on 2021-10-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualConfluenceContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('user_id', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('page_count', models.IntegerField()),
            ],
            options={
                'db_table': 'individual_confluence_contribution',
            },
        ),
        migrations.CreateModel(
            name='IndividualContributionPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('page_name', models.CharField(max_length=256)),
                ('user_id', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'individual_confluence_pages',
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=256)),
                ('meeting_link', models.TextField()),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'meeting_minutes',
            },
        ),
        migrations.CreateModel(
            name='PageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_count', models.IntegerField()),
                ('date', models.IntegerField()),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'page_history',
            },
        ),
        migrations.CreateModel(
            name='RecentComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('page_name', models.CharField(max_length=256)),
                ('updated_time', models.CharField(max_length=256)),
                ('creator', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=2560)),
            ],
            options={
                'db_table': 'confluence_comment',
            },
        ),
        migrations.CreateModel(
            name='RecentPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('page_name', models.CharField(max_length=256)),
                ('updated_time', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=2560)),
                ('action', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'recent_pages',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('picture', models.CharField(max_length=256)),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user_list',
            },
        ),
    ]
