# Generated by Django 3.0.6 on 2021-10-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommitCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('commit_counts', models.CharField(max_length=256)),
                ('query_date', models.IntegerField()),
                ('version', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'git_commit_counts',
            },
        ),
        migrations.CreateModel(
            name='GitMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('file_count', models.IntegerField()),
                ('class_count', models.IntegerField()),
                ('function_count', models.IntegerField()),
                ('code_lines_count', models.IntegerField()),
                ('declarative_lines_count', models.IntegerField()),
                ('executable_lines_count', models.IntegerField()),
                ('comment_lines_count', models.IntegerField()),
                ('comment_to_code_ratio', models.FloatField()),
                ('release', models.CharField(default='', max_length=256)),
                ('sum_cyclomatic_complexity', models.IntegerField(default=0)),
                ('all_methods', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'git_metrics',
            },
        ),
        migrations.CreateModel(
            name='StudentCommitCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=256)),
                ('relation_id', models.CharField(max_length=256, null=True)),
                ('commit_counts', models.CharField(max_length=256)),
                ('space_key', models.CharField(max_length=256, null=True)),
                ('version', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'student_commit_counts',
            },
        ),
    ]
