# Generated by Django 3.0.6 on 2021-09-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0003_gitmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcommitcounts',
            name='version',
            field=models.CharField(default='', max_length=256),
        ),
    ]
