# Generated by Django 3.0.6 on 2021-09-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0004_studentcommitcounts_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommitcounts',
            name='version',
            field=models.CharField(default='', max_length=256),
        ),
    ]
