# Generated by Django 3.0.6 on 2021-10-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0005_gitcommitcounts_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitmetrics',
            name='release',
            field=models.CharField(default='', max_length=256),
        ),
    ]
