# Generated by Django 3.0.6 on 2021-10-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0006_gitmetrics_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitmetrics',
            name='all_methods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gitmetrics',
            name='sum_cyclomatic_complexity',
            field=models.IntegerField(default=0),
        ),
    ]
